version: '3.6'
services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    expose:
      - "3000"
    image: web-image
    networks:
      - shopping-cart-network
    env_file:
      - .env
  discount:
    image: "hashorg/hash-mock-discount-service"
    ports:
      - 50051:50051
    expose:
      - "50051"
    networks:
      - shopping-cart-network
networks:
  shopping-cart-network:
    external: true
